const defaults = {
  seed: 1337,
  hue: 0.05,
  stampDensity: 0.58,
  stampOpacity: 1,
  stampRoughness: 0.5,
  stampSize: [0.36, 0.36],
  texScale: 1,
  blendSharpness: 1,
  normalStrength: 0.2,
  roughness: 0.65,
  metalness: 0.44,
  resolution: 72,
  pixelRatio: 2,
  line1: "THREE.JS",
  line2: "CONF",
  lineSpacing: 1.15,
  matchWidth: true,
  matchDepth: true,
  wireframe: false,
  physics: true,
  returnHome: 8,
  returnSpin: 0.77,
  idle: 0.3,
  cluster: 5,
  clusterRadius: 0.16,
  clusterSettle: 0.5,
  hoverStrength: 0.12,
  hoverRadius: 0.35,
  holdPull: 14,
  holdRadius: 0.6,
  clickStrength: 40,
  clickRadius: 0.5,
  clickSpin: 1,
  cursorLight: true,
  cursorLightIntensity: 6,
  cursorLightRange: 8,
  cursorLightOffset: 0.8,
  lightPhysics: false,
  lightMass: 0.4,
  lightFollow: 60,
  keyColor: "#ffffff",
  keyIntensity: 3,
  backlight: 1,
  skyColor: "#7cbfff",
  groundColor: "#3006b5",
  skyIntensity: 2,
  rim: 1.2,
  rimPower: 2,
  cursorLightColor: "#e04f00",
  cursorShadow: 1,
  cursorShadowSteps: 12,
  cursorShadowThickness: 1.9,
  cursorShadowSoftness: 0.11,
  cursorShadowRays: 5,
  debugView: "beauty",
  showStats: true,
  debugColliders: false,
  debugVelocity: false,
  debugSpin: false,
  debugForces: false,
  debugContacts: false,
  debugHome: false,
  debugVectorScale: 0.25,
  sound: true,
  volume: 1,
  swishLevel: 1,
  spinLevel: 1,
  impactLevel: 1,
  soundTone: 1,
  pauseFade: 0.35,
  spatial: 0.89,
  doppler: 1,
  hrtf: false,
  reverb: 0.5,
  reverbSize: 3.5,
  lightSphere: 1,
  drone: 1,
  droneTone: 1,
  impactDecay: 0.7,
  impactPitch: 1.6,
  massVariation: 0.6,
  pitchBySize: 0.6,
  falloff: "soft",
  clickBuildup: 1.17,
  buildupDecay: 1.6,
  shutter: 0.5,
  blurSamples: 16,
  maxBlur: 0.06,
  bloom: 0.4,
  bloomRadius: 3,
  chromatic: 12,
  vignette: 0.35,
  dither: 1,
  fxaa: 1,
  fogDensity: 0.02,
  sss: 0.6,
  sssPower: 3,
  sssDistortion: 0.35,
  sssDensity: 14,
  envMapIntensity: 1,
  exposure: 1,
  hueSpread: 1,
  saturation: 0.7,
  lightness: 0.5,
  aoRadius: 20,
  aoStrength: 1.22,
  aoBias: 0.05,
  shadowStrength: 0.66,
  shadowRadius: 3,
  shadowBias: 0.001,
  capHeight: 1.4,
  depth: 0.6,
  round: 1,
  normalSmooth: 0.5,
  edge: "round",
  curveSteps: 10,
};

const QUALITY = {
  low: {
    pixelRatio: 1,
    resolution: 48, curveSteps: 4, normalSmooth: 0,
    cursorShadow: 0, cursorShadowRays: 1, cursorShadowSteps: 6,
    shutter: 0, blurSamples: 4, bloom: 0, chromatic: 0, hrtf: false,
  },
  medium: {
    pixelRatio: 1.5,
    resolution: 56, curveSteps: 6, normalSmooth: 0.5,
    cursorShadow: 1, cursorShadowRays: 3, cursorShadowSteps: 8,
    shutter: 0.5, blurSamples: 8, bloom: 0.4, chromatic: 0, hrtf: false,
  },
  high: {
    pixelRatio: 2,
    resolution: 72, curveSteps: 10, normalSmooth: 0.5,
    cursorShadow: 1, cursorShadowRays: 5, cursorShadowSteps: 12,
    shutter: 0.5, blurSamples: 16, bloom: 0.4, chromatic: 12, hrtf: false,
  },
  ultra: {
    pixelRatio: 2,
    resolution: 128, curveSteps: 14, normalSmooth: 0.5,
    cursorShadow: 1, cursorShadowRays: 8, cursorShadowSteps: 20,
    shutter: 0.5, blurSamples: 32, bloom: 0.5, chromatic: 12, hrtf: true,
  },
};

export { defaults, QUALITY };
